name: code_union_task
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

    

  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:
  fonts:
      - family: Manrope
        fonts:
          - asset: fonts/Manrope/Manrope-Regular.ttf
          - asset: fonts/Manrope/Manrope-Bold.ttf
          - asset: fonts/Manrope/Manrope-ExtraBold.ttf
          - asset: fonts/Manrope/Manrope-ExtraLight.ttf
          - asset: fonts/Manrope/Manrope-Light.ttf
          - asset: fonts/Manrope/Manrope-Medium.ttf
          - asset: fonts/Manrope/Manrope-SemiBold.ttf
          
          
          


 
  uses-material-design: true

 
    