name: code_union_task
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

    

  
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  flutter_secure_storage: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:
  fonts:
      - family: Manrope
        fonts:
          - asset: lib/fonts/Manrope/Manrope-Regular.ttf
          - asset: lib/fonts/Manrope/Manrope-Bold.ttf
          - asset: lib/fonts/Manrope/Manrope-ExtraBold.ttf
          - asset: lib/fonts/Manrope/Manrope-ExtraLight.ttf
          - asset: lib/fonts/Manrope/Manrope-Light.ttf
          - asset: lib/fonts/Manrope/Manrope-Medium.ttf
          - asset: lib/fonts/Manrope/Manrope-SemiBold.ttf
  assets:
    - assets/image/
          
          
          


 
  uses-material-design: true

 
    